// PawServe Breed Database — curated for the Breed Finder, Categories & Identifier

export type BreedCategory =
  | 'Security & Guard'
  | 'Herding'
  | 'Working'
  | 'Sporting'
  | 'Hound'
  | 'Terrier'
  | 'Toy'
  | 'Non-Sporting';

export type BreedSize = 'Toy' | 'Small' | 'Medium' | 'Large' | 'Giant';

export interface DogBreed {
  id: string;
  name: string;
  category: BreedCategory;
  size: BreedSize;
  weight: string;
  height: string;
  lifespan: string;
  energy: number;
  trainability: number;
  temperament: string[];
  goodWith: string[];
  purpose: string;
  origin: string;
  image: string;
  description: string;
  funFact: string;
  priceRange: string;
  adoptionAvailability: 'High' | 'Medium' | 'Low';
  colors: string[];
}

export const breedCategories: { id: BreedCategory; label: string; description: string }[] = [
  { id: 'Security & Guard', label: 'Security & Guard', description: 'Protective, loyal, and alert — natural guardians of home and family.' },
  { id: 'Herding', label: 'Herding', description: 'Brilliant and tireless — bred to control the movement of other animals.' },
  { id: 'Working', label: 'Working', description: 'Strong, dependable helpers — from pulling sleds to guarding livestock.' },
  { id: 'Sporting', label: 'Sporting', description: 'Energetic, friendly retrievers and pointers — born for the field and family.' },
  { id: 'Hound', label: 'Hound', description: 'Scent and sight specialists — driven by an extraordinary nose.' },
  { id: 'Terrier', label: 'Terrier', description: 'Feisty, fearless diggers — small dogs with huge personalities.' },
  { id: 'Toy', label: 'Toy', description: 'Tiny companions with big hearts — bred for love and laps.' },
  { id: 'Non-Sporting', label: 'Non-Sporting', description: 'A diverse, charming group — from the dignified to the delightful.' },
];

const img = (id: string) => `https://images.unsplash.com/${id}?w=800&h=600&fit=crop`;

export const breeds: DogBreed[] = [
  {
    id: 'german-shepherd',
    name: 'German Shepherd',
    category: 'Security & Guard',
    size: 'Large',
    weight: '50–90 lb',
    height: '22–26 in',
    lifespan: '9–13 years',
    energy: 4,
    trainability: 5,
    temperament: ['Confident', 'Courageous', 'Loyal', 'Intelligent'],
    goodWith: ['Families', 'Active owners', 'Experienced handlers'],
    purpose: 'Guard dog, police & military work, herding, service dog',
    origin: 'Germany',
    image: img('photo-1551717743-49959800b1f6'),
    description: "The German Shepherd is the world's quintessential working dog — intelligent, versatile, and unwaveringly loyal.",
    funFact: 'German Shepherds were used as messenger dogs, rescue dogs, and guard dogs during both World Wars.',
    priceRange: '$800–$3,500',
    adoptionAvailability: 'Medium',
    colors: ['Black & Tan', 'Sable', 'Solid Black'],
  },
  {
    id: 'rottweiler',
    name: 'Rottweiler',
    category: 'Security & Guard',
    size: 'Large',
    weight: '80–135 lb',
    height: '22–27 in',
    lifespan: '9–10 years',
    energy: 3,
    trainability: 4,
    temperament: ['Confident', 'Calm', 'Protective', 'Devoted'],
    goodWith: ['Families', 'Experienced owners', 'Homes with space'],
    purpose: 'Guard dog, protection, family companion',
    origin: 'Germany',
    image: img('photo-1568393691622-c7ba131d63b4'),
    description: 'Rottweilers are calm, confident, and courageous. With firm training they are gentle family guardians.',
    funFact: 'Rottweilers descended from Roman drover dogs that guarded herds and pulled carts for butchers.',
    priceRange: '$1,000–$4,000',
    adoptionAvailability: 'Medium',
    colors: ['Black & Mahogany'],
  },
  {
    id: 'doberman-pinscher',
    name: 'Doberman Pinscher',
    category: 'Security & Guard',
    size: 'Large',
    weight: '60–100 lb',
    height: '24–28 in',
    lifespan: '10–13 years',
    energy: 4,
    trainability: 5,
    temperament: ['Alert', 'Fearless', 'Loyal', 'Energetic'],
    goodWith: ['Active owners', 'Families', 'Guard-dog seekers'],
    purpose: 'Protection, police work, family companion',
    origin: 'Germany',
    image: img('photo-1591608971362-08b2a757529a'),
    description: 'Sleek, powerful, and highly intelligent — a top-tier protection dog and devoted family companion.',
    funFact: 'Developed in the 1890s by Karl Friedrich Louis Dobermann, a tax collector who wanted a loyal guard dog.',
    priceRange: '$1,200–$3,800',
    adoptionAvailability: 'Low',
    colors: ['Black & Rust', 'Red & Rust'],
  },
  {
    id: 'border-collie',
    name: 'Border Collie',
    category: 'Herding',
    size: 'Medium',
    weight: '30–55 lb',
    height: '18–22 in',
    lifespan: '12–15 years',
    energy: 5,
    trainability: 5,
    temperament: ['Brilliant', 'Energetic', 'Eager', 'Work-driven'],
    goodWith: ['Active owners', 'Runners', 'Homes with land'],
    purpose: 'Herding, dog sports, agility, obedience',
    origin: 'United Kingdom',
    image: img('photo-1503256207526-0d5d80fa2f47'),
    description: 'Widely considered the most intelligent dog breed — a bundle of energy and focus that needs serious exercise.',
    funFact: 'A Border Collie named Chaser learned the names of over 1,000 objects.',
    priceRange: '$700–$2,500',
    adoptionAvailability: 'Medium',
    colors: ['Black & White', 'Red & White', 'Blue Merle'],
  },
  {
    id: 'australian-shepherd',
    name: 'Australian Shepherd',
    category: 'Herding',
    size: 'Medium',
    weight: '40–65 lb',
    height: '18–23 in',
    lifespan: '12–15 years',
    energy: 5,
    trainability: 5,
    temperament: ['Smart', 'Playful', 'Loyal', 'Energetic'],
    goodWith: ['Active families', 'Outdoor enthusiasts', 'Sport homes'],
    purpose: 'Herding, dog sports, companionship',
    origin: 'United States',
    image: img('photo-1558788353-f76d92427f16'),
    description: 'Despite its name, developed in the American West. Intelligent, energetic, and a favorite for agility.',
    funFact: 'Often born with a naturally bobbed tail — some have two different-colored eyes.',
    priceRange: '$800–$2,800',
    adoptionAvailability: 'Medium',
    colors: ['Blue Merle', 'Red Merle', 'Black', 'Red'],
  },
  {
    id: 'pembroke-welsh-corgi',
    name: 'Pembroke Welsh Corgi',
    category: 'Herding',
    size: 'Small',
    weight: '25–30 lb',
    height: '10–12 in',
    lifespan: '12–15 years',
    energy: 4,
    trainability: 4,
    temperament: ['Affectionate', 'Bold', 'Smart', 'Playful'],
    goodWith: ['Families', 'Apartments', 'First-time owners'],
    purpose: 'Herding, companionship',
    origin: 'Wales',
    image: img('photo-1612536057832-2ff7ead58194'),
    description: 'A big dog in a small package — lively, intelligent, and famously loved by the British royal family.',
    funFact: 'Queen Elizabeth II owned more than 30 Pembroke Welsh Corgis during her lifetime.',
    priceRange: '$1,000–$3,000',
    adoptionAvailability: 'Low',
    colors: ['Red & White', 'Sable', 'Tri-color'],
  },
  {
    id: 'siberian-husky',
    name: 'Siberian Husky',
    category: 'Working',
    size: 'Medium',
    weight: '35–60 lb',
    height: '20–24 in',
    lifespan: '12–14 years',
    energy: 5,
    trainability: 3,
    temperament: ['Friendly', 'Mischievous', 'Independent', 'Athletic'],
    goodWith: ['Active owners', 'Families', 'Cold climates'],
    purpose: 'Sled pulling, companionship',
    origin: 'Siberia, Russia',
    image: img('photo-1605568427561-40dd23c2acea'),
    description: 'A stunning, energetic sled dog with a friendly, sometimes mischievous nature. Needs lots of exercise.',
    funFact: 'In 1925, a team led by Balto delivered life-saving diphtheria serum across 674 miles of Alaskan wilderness.',
    priceRange: '$800–$2,500',
    adoptionAvailability: 'High',
    colors: ['Black & White', 'Gray & White', 'Red & White'],
  },
  {
    id: 'boxer',
    name: 'Boxer',
    category: 'Working',
    size: 'Large',
    weight: '55–80 lb',
    height: '21–25 in',
    lifespan: '10–12 years',
    energy: 4,
    trainability: 3,
    temperament: ['Playful', 'Patient', 'Protective', 'Silly'],
    goodWith: ['Families with kids', 'Active owners'],
    purpose: 'Guard dog, companion, service work',
    origin: 'Germany',
    image: img('photo-1543466835-00a7907e9de1'),
    description: 'Energetic, playful, and famously patient with children — the "Peter Pan" of dogs.',
    funFact: 'Boxers got their name from the way they "box" with their front paws when playing.',
    priceRange: '$900–$2,800',
    adoptionAvailability: 'High',
    colors: ['Fawn', 'Brindle', 'White'],
  },
  {
    id: 'great-dane',
    name: 'Great Dane',
    category: 'Working',
    size: 'Giant',
    weight: '110–175 lb',
    height: '28–34 in',
    lifespan: '7–10 years',
    energy: 3,
    trainability: 3,
    temperament: ['Gentle', 'Friendly', 'Patient', 'Dignified'],
    goodWith: ['Families', 'Homes with space', 'Calm owners'],
    purpose: 'Companion, estate guarding',
    origin: 'Germany',
    image: img('photo-1596492784531-6e6eb5ea9993'),
    description: "The 'Apollo of Dogs' — gentle, affectionate, and enormous. Often thinks it's a lap dog.",
    funFact: 'The tallest dog ever recorded was a Great Dane named Zeus at 44 inches at the shoulder.',
    priceRange: '$1,000–$3,000',
    adoptionAvailability: 'Low',
    colors: ['Fawn', 'Brindle', 'Blue', 'Black', 'Harlequin'],
  },
  {
    id: 'labrador-retriever',
    name: 'Labrador Retriever',
    category: 'Sporting',
    size: 'Large',
    weight: '55–80 lb',
    height: '21–24 in',
    lifespan: '10–12 years',
    energy: 4,
    trainability: 5,
    temperament: ['Friendly', 'Outgoing', 'Eager', 'Gentle'],
    goodWith: ['Families', 'First-time owners', 'Kids'],
    purpose: 'Retrieving, service work, companionship',
    origin: 'Canada',
    image: img('photo-1552053831-71594a27632d'),
    description: "America's most popular breed for decades — friendly, eager to please, and endlessly versatile.",
    funFact: 'Labradors have been the most registered breed with the AKC every year since 1991.',
    priceRange: '$800–$2,500',
    adoptionAvailability: 'High',
    colors: ['Yellow', 'Chocolate', 'Black'],
  },
  {
    id: 'golden-retriever',
    name: 'Golden Retriever',
    category: 'Sporting',
    size: 'Large',
    weight: '55–75 lb',
    height: '21–24 in',
    lifespan: '10–12 years',
    energy: 4,
    trainability: 5,
    temperament: ['Friendly', 'Intelligent', 'Trustworthy', 'Devoted'],
    goodWith: ['Families', 'First-time owners', 'Kids'],
    purpose: 'Retrieving, service & therapy work, companionship',
    origin: 'Scotland',
    image: img('photo-1558788353-f76d92427f16'),
    description: 'The gold standard of family dogs — patient, friendly, and a top choice for therapy work.',
    funFact: 'Developed in Scotland by Lord Tweedmouth, who crossed a yellow Retriever with a Tweed Water Spaniel.',
    priceRange: '$900–$3,000',
    adoptionAvailability: 'High',
    colors: ['Golden', 'Light Golden', 'Dark Golden'],
  },
  {
    id: 'beagle',
    name: 'Beagle',
    category: 'Hound',
    size: 'Small',
    weight: '20–30 lb',
    height: '13–15 in',
    lifespan: '12–15 years',
    energy: 4,
    trainability: 3,
    temperament: ['Curious', 'Friendly', 'Merry', 'Determined'],
    goodWith: ['Families', 'Kids', 'First-time owners'],
    purpose: 'Scent hunting, companionship',
    origin: 'England',
    image: img('photo-1517849845537-4d257902454a'),
    description: 'A small, merry hound with a legendary nose. Friendly and curious — though its nose can lead it into trouble.',
    funFact: "Snoopy, the world's most famous cartoon dog, is a Beagle.",
    priceRange: '$600–$2,000',
    adoptionAvailability: 'High',
    colors: ['Tri-color', 'Lemon & White', 'Red & White'],
  },
  {
    id: 'dachshund',
    name: 'Dachshund',
    category: 'Hound',
    size: 'Small',
    weight: '16–32 lb',
    height: '8–9 in',
    lifespan: '12–16 years',
    energy: 3,
    trainability: 3,
    temperament: ['Bold', 'Curious', 'Stubborn', 'Lively'],
    goodWith: ['Families', 'Apartments', 'Adults'],
    purpose: 'Badger hunting, companionship',
    origin: 'Germany',
    image: img('photo-1612195583950-b8fd34c87093'),
    description: 'The "wiener dog" — small with a big personality. Brave, curious, and still loves to dig and chase.',
    funFact: 'Bred with short legs and long bodies specifically to fit into badger burrows.',
    priceRange: '$700–$2,500',
    adoptionAvailability: 'Medium',
    colors: ['Red', 'Black & Tan', 'Chocolate', 'Dapple'],
  },
  {
    id: 'greyhound',
    name: 'Greyhound',
    category: 'Hound',
    size: 'Large',
    weight: '60–70 lb',
    height: '27–30 in',
    lifespan: '10–14 years',
    energy: 3,
    trainability: 3,
    temperament: ['Gentle', 'Quiet', 'Calm', 'Sweet'],
    goodWith: ['Apartments', 'Families', 'Seniors'],
    purpose: 'Coursing, racing, companionship',
    origin: 'Egypt / Middle East',
    image: img('photo-1591608971362-08b2a757529a'),
    description: "The world's fastest couch potato — a sprinter that is surprisingly calm and gentle at home.",
    funFact: 'Can reach 45 mph — the fastest dog breed and second-fastest land animal after the cheetah.',
    priceRange: '$800–$2,500',
    adoptionAvailability: 'High',
    colors: ['Brindle', 'Fawn', 'Black', 'Blue'],
  },
  {
    id: 'jack-russell-terrier',
    name: 'Jack Russell Terrier',
    category: 'Terrier',
    size: 'Small',
    weight: '13–17 lb',
    height: '10–15 in',
    lifespan: '13–16 years',
    energy: 5,
    trainability: 4,
    temperament: ['Fearless', 'Energetic', 'Clever', 'Tenacious'],
    goodWith: ['Active owners', 'Experienced owners'],
    purpose: 'Fox hunting, companionship, dog sports',
    origin: 'England',
    image: img('photo-1503256207526-0d5d80fa2f47'),
    description: 'A small dog with enormous energy and personality. Fearless, clever, and needs lots of exercise.',
    funFact: 'Moose from the TV show Frasier was a Jack Russell — reportedly the highest-paid dog actor in Hollywood.',
    priceRange: '$600–$2,000',
    adoptionAvailability: 'High',
    colors: ['White with Tan', 'White with Black', 'Tri-color'],
  },
  {
    id: 'staffordshire-bull-terrier',
    name: 'Staffordshire Bull Terrier',
    category: 'Terrier',
    size: 'Medium',
    weight: '24–38 lb',
    height: '14–16 in',
    lifespan: '12–14 years',
    energy: 4,
    trainability: 4,
    temperament: ['Affectionate', 'Courageous', 'Playful', 'Loyal'],
    goodWith: ['Families', 'Kids', 'Active owners'],
    purpose: 'Companion, dog sports',
    origin: 'England',
    image: img('photo-1543466835-00a7907e9de1'),
    description: 'Muscular and courageous with an exceptionally affectionate nature — nicknamed the "nanny dog."',
    funFact: 'One of the few breeds recommended by the UK Kennel Club as especially good with children.',
    priceRange: '$1,000–$2,500',
    adoptionAvailability: 'High',
    colors: ['Red', 'Fawn', 'Brindle', 'Black', 'Blue'],
  },
  {
    id: 'chihuahua',
    name: 'Chihuahua',
    category: 'Toy',
    size: 'Toy',
    weight: '3–6 lb',
    height: '5–8 in',
    lifespan: '14–16 years',
    energy: 3,
    trainability: 3,
    temperament: ['Confident', 'Loyal', 'Sassy', 'Alert'],
    goodWith: ['Apartments', 'Seniors', 'City dwellers'],
    purpose: 'Companionship',
    origin: 'Mexico',
    image: img('photo-1529429617124-95b109e86bb8'),
    description: 'The smallest dog breed with one of the biggest personalities — loyal, alert, and full of attitude.',
    funFact: 'Named after the Mexican state of Chihuahua, where the breed was discovered in the mid-1800s.',
    priceRange: '$600–$2,500',
    adoptionAvailability: 'High',
    colors: ['Fawn', 'Black', 'White', 'Chocolate', 'Cream'],
  },
  {
    id: 'pomeranian',
    name: 'Pomeranian',
    category: 'Toy',
    size: 'Toy',
    weight: '3–7 lb',
    height: '6–7 in',
    lifespan: '12–16 years',
    energy: 3,
    trainability: 3,
    temperament: ['Lively', 'Bold', 'Affectionate', 'Curious'],
    goodWith: ['Apartments', 'Families', 'Seniors'],
    purpose: 'Companionship',
    origin: 'Germany / Poland',
    image: img('photo-1561037404-61cd46aa615b'),
    description: 'A tiny, fluffy ball of energy and confidence — descended from large sled dogs, miniaturized into a lively companion.',
    funFact: 'Two Pomeranians were among only three dogs to survive the sinking of the Titanic.',
    priceRange: '$800–$3,000',
    adoptionAvailability: 'Medium',
    colors: ['Orange', 'Cream', 'Black', 'White', 'Sable'],
  },
  {
    id: 'pug',
    name: 'Pug',
    category: 'Toy',
    size: 'Toy',
    weight: '14–18 lb',
    height: '10–13 in',
    lifespan: '12–15 years',
    energy: 2,
    trainability: 3,
    temperament: ['Charming', 'Mischievous', 'Loving', 'Sociable'],
    goodWith: ['Apartments', 'Families', 'Seniors'],
    purpose: 'Companionship',
    origin: 'China',
    image: img('photo-1517849845537-4d257902454a'),
    description: 'Charming and comical with a wrinkly face and a huge heart. Happiest snuggling on a lap.',
    funFact: 'Pugs were the official dog of the House of Orange after one saved a prince from assassination.',
    priceRange: '$1,000–$3,000',
    adoptionAvailability: 'Medium',
    colors: ['Fawn', 'Black', 'Silver'],
  },
  {
    id: 'french-bulldog',
    name: 'French Bulldog',
    category: 'Non-Sporting',
    size: 'Small',
    weight: '16–28 lb',
    height: '11–13 in',
    lifespan: '10–12 years',
    energy: 2,
    trainability: 3,
    temperament: ['Playful', 'Adaptable', 'Alert', 'Affectionate'],
    goodWith: ['Apartments', 'Families', 'City dwellers'],
    purpose: 'Companionship',
    origin: 'France',
    image: img('photo-1517849845537-4d257902454a'),
    description: 'Playful and adaptable with bat ears and a big personality — one of the world\'s most popular breeds.',
    funFact: 'Surpassed the Labrador in 2022 to become the most popular dog breed in the United States.',
    priceRange: '$2,000–$6,000',
    adoptionAvailability: 'Low',
    colors: ['Brindle', 'Fawn', 'Pied', 'Cream'],
  },
  {
    id: 'poodle',
    name: 'Poodle',
    category: 'Non-Sporting',
    size: 'Medium',
    weight: '40–70 lb',
    height: '15–22 in',
    lifespan: '10–18 years',
    energy: 4,
    trainability: 5,
    temperament: ['Intelligent', 'Active', 'Elegant', 'Loyal'],
    goodWith: ['Families', 'Allergy-sensitive owners', 'Active homes'],
    purpose: 'Companionship, retrieving, dog sports',
    origin: 'Germany / France',
    image: img('photo-1601758228041-f3b2795255f1'),
    description: 'One of the smartest and most versatile breeds. Low-shedding coat makes it popular with allergy sufferers.',
    funFact: 'The elaborate "lion clip" was originally functional — it kept organs warm while reducing drag in water.',
    priceRange: '$1,000–$3,500',
    adoptionAvailability: 'Medium',
    colors: ['White', 'Black', 'Apricot', 'Silver'],
  },
  {
    id: 'dalmatian',
    name: 'Dalmatian',
    category: 'Non-Sporting',
    size: 'Large',
    weight: '45–70 lb',
    height: '19–24 in',
    lifespan: '11–13 years',
    energy: 4,
    trainability: 4,
    temperament: ['Energetic', 'Playful', 'Sensitive', 'Dignified'],
    goodWith: ['Active owners', 'Runners', 'Families'],
    purpose: 'Carriage dog, firehouse mascot, companionship',
    origin: 'Croatia',
    image: img('photo-1552053831-71594a27632d'),
    description: 'Energetic and elegant, famous for its spotted coat. Needs plenty of exercise and companionship.',
    funFact: 'Puppies are born completely white — their spots develop over the first few weeks of life.',
    priceRange: '$800–$2,500',
    adoptionAvailability: 'Medium',
    colors: ['White with Black Spots', 'White with Liver Spots'],
  },
  {
    id: 'boston-terrier',
    name: 'Boston Terrier',
    category: 'Non-Sporting',
    size: 'Small',
    weight: '12–25 lb',
    height: '15–17 in',
    lifespan: '11–13 years',
    energy: 3,
    trainability: 4,
    temperament: ['Friendly', 'Bright', 'Lively', 'Affectionate'],
    goodWith: ['Families', 'Apartments', 'First-time owners'],
    purpose: 'Companionship',
    origin: 'United States',
    image: img('photo-1548199973-03cce0bbc87b'),
    description: 'Friendly and lively with a tuxedo-like coat — nicknamed "the American Gentleman."',
    funFact: 'One of the few breeds developed entirely in the United States, created in Boston in the 1860s.',
    priceRange: '$800–$2,500',
    adoptionAvailability: 'Medium',
    colors: ['Black & White', 'Brindle & White', 'Seal & White'],
  },
];

export const getBreedById = (id: string) => breeds.find((b) => b.id === id);

export const breedsByCategory = (category: BreedCategory) => breeds.filter((b) => b.category === category);
